/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.stanton.kafka.consumer;

import java.util.logging.Logger;

import com.stanton.kafka.api.KafkaConsumerApplication;


public class App {

	public static void main(String[] args) {
		try {
			new KafkaConsumerApplication().run(args);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.exit(-1);
		};
	}
}
